---
- name: Create Configmap
  community.kubernetes.k8s:
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-mariadb'
        namespace: "{{ ansible_operator_meta.namespace }}"
        labels:
          app: mariadb
      data:
        master.cnf: |
          # Apply this config only on the master.
          [mysqld]
          log-bin
        slave.cnf: |
          # Apply this config only on slaves.
          [mysqld]
          super-read-only

- name: Create service
  community.kubernetes.k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-mariadb'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: mariadb
      spec:
        ports:
        - name: mariadb
          port: 3306
        clusterIP: None
        selector:
          app: mariadb

- name: Create pvc
  community.kubernetes.k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: px-mariadb-pvc
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ mariadb_pvc_storage_request }}"

- name: start MariaDB
  community.kubernetes.k8s:
    definition:
      kind: StatefulSet
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-mariadb'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ replicas }}"
        selector:
          matchLabels:
            app: mariadb
        serviceName: '{{ ansible_operator_meta.name }}-mariadb'
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: mariadb
          spec:
            containers:
            - name: mariadb
              image: "docker.io/mariadb:latest"
              imagePullPolicy: Always
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: "{{ mariadbpass }}"
              ports:
              - name: mariadb
                containerPort: 3306
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
              livenessProbe:
                tcpSocket:
                  port: mariadb
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                tcpSocket:
                  port: mariadb
                initialDelaySeconds: 5
                timeoutSeconds: 2
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: mariadb-data
            volumes:
            - name: mariadb-data
              persistentVolumeClaim:
                claimName: px-mariadb-pvc
