---
- name: Create pvc
  community.kubernetes.k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: px-mariadb-pvc
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ mariadb_pvc_storage_request }}"

- name: start MariaDB
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-mariadb'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ replicas }}"
        selector:
          matchLabels:
            app: mariadb
        template:
          metadata:
            labels:
              app: mariadb
          spec:
            containers:
            - name: mariadb
              image: "docker.io/mariadb:latest"
              imagePullPolicy: "Always"
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: "{{ mariadbpass }}"
              ports:
              - containerPort: 3306
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: mariadb-data
            volumes:
            - name: mariadb-data
              persistentVolumeClaim:
                claimName: px-mariadb-pvc
