apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: mariadb-operator
  name: mariadb-operator
---
apiVersion: mariadb.operator/v1
kind: MariaDB
metadata:
  name: mariadb-sample
  namespace: mariadb-operator
spec:
  replicas: 1
  mariadbpass: password
  mariadb_pvc_storage_request: 1Gi
