---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mariadbs.mariadb.operator
spec:
  group: mariadb.operator
  names:
    kind: MariaDB
    listKind: MariaDBList
    plural: mariadbs
    singular: mariadb
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: MariaDB is the Schema for the mariadbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MariaDB
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              mariadbpass:
                description: Database additional user password (base64 encoded)
                type: string
              size:
                description: Size is the size of the deployment
                format: int32
                type: integer
            required:
            - mariadbpass
            - size
          status:
            description: Status defines the observed state of MariaDB
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
